export const randomObjectNames = [
  "House",
  "Ice Pick",
  "Spatula",
  "Giraffe",
  "Ipod Charger",
  "Ring",
  "Slipper",
  "Pair Of Safety Goggles",
  "Mp3 Player",
  "Wine Glass",
  "Chocolate",
  "Comic Book",
  "Cars",
  "Book Of Matches",
  "Frying Pan",
  "Spool Of Ribbon",
  "Mobile Phone",
  "Stockings",
  "Washcloth",
  "Pen",
  "Computer",
  "Bowl",
  "Sponge",
  "Hand Mirror",
  "Buckle",
  "Rubber Stamp",
  "Chain",
  "Hair Ribbon",
  "Wrench",
  "Video Games",
  "Pair Of Dice",
  "Lamp",
  "Game CD",
  "Cucumber",
  "Paper",
  "Can Of Peas",
  "Game Cartridge",
  "Toe Ring",
  "Rug",
  "Toothpaste",
  "Deodorant",
  "Leg Warmers",
  "Tomato",
  "Shoes",
  "Word Search",
  "Piece Of Gum",
  "Turtle",
  "Chapter Book",
  "Sticker Book",
  "Bookmark",
  "Jar Of Jam",
  "Beef",
  "Chicken",
  "Box Of Chalk",
  "Can Of Chili",
  "Picture Frame",
  "Pair Of Scissors",
  "Lighter",
  "Package Of Crisp And Crunchy Edibles",
  "Fake Flowers",
  "Container Of Pudding",
  "Sofa",
  "Flyswatter",
  "Nail",
  "Sketch Pad",
  "Bow Tie",
  "Zipper",
  "Sand Paper",
  "Ipod",
  "Pair Of Glasses",
  "Hair Brush",
  "Tennis Racket",
  "Bottle Of Sunscreen",
  "Drill Press",
  "Cellphone",
  "Chair",
  "Book",
  "Table",
  "Lemon",
  "Pocketwatch",
  "Puddle",
  "Paperclip",
  "CD",
  "Teddies",
  "Hanger",
  "Box",
  "Pocketknife",
  "Purse",
  "Pair Of Tongs",
  "Belt",
  "Spool Of String",
  "Bouquet Of Flowers",
  "Cowboy Hat",
  "Grid Paper",
  "Empty Bottle",
  "Hand Fan",
  "Cup",
  "Photo Album",
  "Eraser",
  "Floor",
  "Hair Tie",
  "Sun Glasses",
  "Trucks",
  "Sandglass",
  "Thimble",
  "Jar Of Pickles",
  "Model Car",
  "Drawer",
  "Lion",
  "Plush Cat",
  "Bed",
  "Shovel",
  "Empty Tin Can",
  "Candle",
  "Whistle",
  "Handbasket",
  "Bottle Of Paint",
  "Tube Of Lipstick",
  "Egg",
  "Pair Of Rubber Gloves",
  "Baseball Bat",
  "Shark",
  "Spring",
  "Desk",
  "Vase",
  "Snail Shell",
  "Bottle Of Water",
  "Kitchen Knife",
  "Bag Of Popcorn",
  "Water Bottle",
  "Key",
  "Wedding Ring",
  "Tire Swing",
  "Balloon",
  "Pillow",
  "Phone",
  "Keychain",
  "Baseball",
  "Flashlight",
  "Toy Top",
  "Bottle",
  "Chalk",
  "Carrots",
  "Scotch Tape",
  "Lamp Shade",
  "Rolling Pin",
  "Tooth Pick",
  "Spectacles",
  "Feather",
  "Harmonica",
  "Face Wash",
  "Pencil Holder",
  "Door",
  "Roll Of Stickers",
  "Egg Timer",
  "Plush Unicorn",
  "Bag Of Rubber Bands",
  "Soccer Ball",
  "Cement Stone",
  "Hand Bag",
  "Pair Of Socks",
  "Magnet",
  "Clay Pot",
  "Toy Soldier",
  "Soap",
  "Roll Of Toilet Paper",
  "Scarf",
  "Fridge",
  "Ocarina",
  "Map",
  "Sticky Note",
  "Rhino",
  "Bread",
  "Box Of Baking Soda",
  "Handheld Game System",
  "Notepad",
  "Water",
  "Acorn",
  "Spoon",
  "Shirt",
  "Bottle Cap",
  "Panda",
  "Banana",
  "Helmet",
  "Nail Filer",
  "Toy Robot",
  "Wristwatch",
  "Tree",
  "Plush Dog",
  "Screw",
  "Tea Pot",
  "Cookie Tin",
  "Bottle Of Glue",
  "Salt Shaker",
  "Martini Glass",
  "Toothbrush",
  "Bottle Of Lotion",
  "Domino Set",
  "Rope",
  "Candy Cane",
  "Paint Brush",
  "Couch",
  "Fish",
  "Roll Of Masking Tape",
  "Miniature Portrait",
];
